name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > SCM.pem
          chmod 600 SCM.pem

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2  # 서울 서버로 변경

      - name: Deploy Backend
        run: |
          ssh -o StrictHostKeyChecking=no -i "SCM.pem" ubuntu@13.124.185.83 <<EOF
          cd ~/JourneyMate_AWS/23_HF124-Backend
          npm install
          npm start &
          sleep 20
          EOF
          

      - name: Deploy Frontend
        run: |
          ssh -o StrictHostKeyChecking=no -i "SCM.pem" ubuntu@13.124.185.83 <<EOF
          cd ~/JourneyMate_AWS/23_HF124-Frontend
          npm install
          npm start &
          EOF
